import banner1 from "../assets/images/banner/banner1.jpg";
import banner2 from "../assets/images/banner/banner2.jpg";
import banner3 from "../assets/images/banner/banner3.jpg"; 
import notice1 from "../assets/images/notice1.jpg";
import notice2 from "../assets/images/notice2.jpg";
import notice3 from "../assets/images/notice3.jpg";
import notice4 from "../assets/images/notice4.jpg";
import gallery1 from "../assets/images/gallery1.jpg";
import gallery2 from "../assets/images/gallery2.jpg";
import gallery3 from "../assets/images/gallery3.jpg";
import gallery4 from "../assets/images/gallery4.jpg";
import gallery5 from "../assets/images/gallery5.jpg";
import gallery6 from "../assets/images/gallery6.jpg";
import ministries from "../assets/images/ministries.jpg";
import ministry1 from "../assets/images/ministry1.jpg";
import ministry2 from "../assets/images/ministry2.jpg";
import ministry3 from "../assets/images/ministry3.jpg";
import ministry4 from "../assets/images/ministry4.jpg";
import training from "../assets/images/training.jpg";
import member1 from "../assets/images/member1.jpg";
import member2 from "../assets/images/member2.jpg";
import member3 from "../assets/images/member3.jpg";
import member4 from "../assets/images/member4.jpg";
import member5 from "../assets/images/member5.jpg";
import notices from "../assets/images/notices.jpg";
import about from "../assets/images/about.jpg";
import about_banner from "../assets/images/about_banner.jpg";
import article1 from "../assets/images/article1.jpg";
import article2 from "../assets/images/article2.jpg";
import article3 from "../assets/images/article3.jpg";
import article4 from "../assets/images/article4.jpg";

const staticImages = {banner1, banner2, banner3, notice1, notice2, notice3, notice4, gallery1, gallery2, gallery3, gallery4, gallery5, gallery6, ministries, ministry1, ministry2, ministry3, ministry4, training, member1, member2, member3, member4, member5, notices, about_banner, about, article1, article2, article3, article4 };
export default staticImages;